work_dir: /content/drive/MyDrive/Fall-Detection/work_dir/yolo_blockgcn

# feeder
feeder: feeders.feeder_yolo.Feeder
train_feeder_args:
  data_path: /content/drive/MyDrive/Fall-Detection/dataset/yolo_pose/NTU60_YOLO_CS_binary_fall.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: True
  window_size: 64
  normalization: False
  random_rot: False          # YOLO data 2D — jangan aktifkan random_rot
  p_interval: [0.5, 1.0]
  vel: False
  bone: False

test_feeder_args:
  data_path: /content/drive/MyDrive/Fall-Detection/dataset/yolo_pose/NTU60_YOLO_CS_binary_fall.npz
  split: test
  window_size: 64
  p_interval: [1.0, 1.0]
  vel: False
  bone: False
  debug: False

# model
model: model.BlockGCN.Model
model_args:
  num_class: 2
  num_point: 17              # COCO 17-joint
  num_person: 1              # M=1
  graph: graph.coco_yolo.Graph
  window_size: 64
  graph_args:
    labeling_mode: "spatial"
  joint_label:
    [0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2, 1, 1, 3, 3, 3, 3]

# optim — identik dengan colab.yaml asli (lr lebih kecil karena resume/fine-tune)
weight_decay: 0.0004
base_lr: 0.001
lr_decay_rate: 0.1
step: [40, 60]
warm_up_epoch: 5

# training
device: [0]
num_worker: 8
batch_size: 8
test_batch_size: 8
num_epoch: 80
nesterov: True
save_epoch: 0
show_topk: [1]
